

- name: Copy file between Windows servers
  hosts: all
  tasks:
    - name: Copy file from source to destination
      win_copy:
        src: \\ptl.local\public\userdata\shared-files\ChromeSetup.exe
        dest: C:\Temp\ChromeSetup.exe
