---
- name: Copy file to multiple destination servers
  hosts: source_server
  become: true
  tasks:
    - name: Use robocopy to transfer file
      ansible.windows.win_command: >
        robocopy 'C:\temp\source' '\\{{ item }}\C$\temp\dest-file.txt'
      loop:
        - destination_server1
        - destination_server2
        - destination_server3
        - destination_server4
