---
- name: Copy a single file
  hosts: all
  become: false
  gather_facts: false
  tasks:
  - name: Copy a single file
    ansible.windows.win_copy:
      src: /impfile.txt
      dest: C:\Temp\impfile.txt
