---
- name: Copy files from source server to other Windows hosts
  hosts: all
  gather_facts: false
  tasks:
    - name: Copy files from source server
      ansible.windows.win_copy:
        #src: "\\\\node1.ptl.local\\c$\\temp\\"
        src: "\\\\DC2.ptl.local\wallpapers-folder-data\\"
        dest: "C:\\temp\\new"
        remote_src: true
