- name: Power on VMware VM
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Power on VM
      community.vmware.vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: false
        datacenter: "PUNE-DC"        # must match your vSphere datacenter name
        #name: "{{ vm_name }}"        # VM display name in vCenter
        name: vm1
        state: poweredon
      delegate_to: localhost
