---
- hosts: AWX-server
  #become: true
  #become_user: pradip
  tasks:
    - name: Create directory for daily logs with command module
      ansible.builtin.command:
        cmd: "mkdir -p /var/logs/app/daily_logs"
